replace functions

replacedict ={
    "accomplish": "do",
    "accomplished": "did",
    "ascertain": "find out",
    "disseminate": "send out",
    "endeavor": "try",
    "expedite": "speed up",
    "facilitate": "help",
    "formulate": "form",
    "in lieu of": "instead of",
    "locality": "place",
    "optimum": "best",
    "strategize": "plan",
    "utilize": "use",
    "with regard to": "about",
    "by means of": "by",
    "in the event that": "if",
    "until such time": "until",
    "during such time": "while",
    "during the time": "while",
    "in respect of": "for",
    "in view of the fact": "because",
    "on the part of": "by",
    "subsequent to": "after",
    "under the provisions of": "under",
    "with a view to": "to",
    "it would appear that": "apparently",
    "it is probable that": "probably",
    "notwithstanding the fact that": "although",
    "adequate number of": "enough",
    "excessive number of": "too many",
    "some of the various ways": "methods",
    "adequate number":"enough",
    "adequate number of":"enough of",
    "adjacent to":"by",
    "afford an opportunity":"give",
    "ahead of schedule":" early",
    "almost all":"most",
    "along the lines of ":"like",
    "an estimated":"about",
    "arrange to return":"return",
    "as a consequence of":"because",
    "as a result of":"because",
    "as a means of":"to",
    "as long as":"if",
    "as of now":"about",
    "as regards":"about",
    "assuming that":"if",
    "as well as":"also",
    "at all times":"always",
    "attached herewith is":" here's",
    "at the end of":"after",
    "at the time":"when",
    "because of the fact that":"since",
    "by reason of":"because of",
    "by the name of":"named",
    "by virtue of":"by",
    "came to an agreement":"agreed",
    "carry out an evaluation of":"evaluate",
    "come to an agreement":"agree",
    "come to an end":"stop",
    "comply with":"obey",
    "conduct an investigation":"investigate",
    "conduct a review of":"review",
    "conduct experiments":"experiment",
    "contiguous to":"next to",
    "course of":"during",
    "despite the fact that":"despite",
    "draw attention to":"announce",
    "due to the fact that":"because",
    "effect many changes":" change",
    "employment opportunities":"jobs",
    "except when":"unless",
    "excessive number":"too many",
    "extend an invitation":"invite",
    "for the purpose of":" to",
    "for the reason that":"because",
    "from the point of view of":"from",
    "give an indication of":"show",
    "give rise to":"lead to",
    "give consideration to":"consider",
    "has the ability to":"can",
    "has the capability to":"can",
    "have an effect on":"affect",
    "hold a conference":"confer",
    "in back of":"behind",
    "in conjunction with":"along with",
    "in connection with":"with",
    "in excess of":"more than",
    "in favor of":"for",
    "in order to":"to",
    "in place of":"for",
    "in proximity to":"close to, near",
    "in reference to":"about",
    "in regard to":"about",
    "in relation to":"about",
    "in spite of":"despite",
    "in the absence of":"without",
    "in the amount of":"for",
    "in the case of":"in",
    "in the context of":"in",
    "in the course of":"during",
    "in the event that":"should",
    "in the nature of":"like",
    "in the neighborhood of":"roughly",
    "in the near future":"soon",
    "in the vicinity of":"close to",
    "in view of the fact":"because, since, for, given, when",
    "is able to":"can",
    "it would appear that":"apparently",
    "it is probable that":"probably",
    "made a statement":"said",
    "make an application":"apply",
    "make an examination of":"examine",
    "make reference to":"refer to",
    "none at all":"none",
    "not in a position to":"cannot",
    "not many":"few",
    "not old enough":"too young",
    "not possible":"impossible",
    "not the same":"different",
    "notwithstanding the fact that":"although,",
    "on a daily basis":"daily",
    "on a regular basis":"daily",
    "on behalf of":"for",
    "on most occasions":"usually",
    "opt for":"choose",
    "over the duration of":"throughout",
    "per annum":"for each year",
    "per diem":"for each day",
    "perform an assessment of":"assess",
    "present time":"present",
    "previous to":"before",
    "provided that":"if",
    "regards to":"about",
    "relating to":"about",
    "result in":"lead to",
    "some of the":"some",
    "submit an application for":"apply for",
    "subsequent to":"following",
    "sufficient number (of)":"enough",
    "take action":"act",
    "the question as to whether":"the question whether",
    "to a certain degree":"in part",
    "to whatever extent":"however",
    "under the provisions of":"under",
    "use up":"use",
    "with the exception of":"except for"
    

}
